### ISSUE TITLE
Fail to build project on Windows10/Intellij 2019.3.1

### ISSUE THREAD

**Issue by stef-pellegrino** [fxrobin/XenonReborn#1]
Compiling seems ok, but If I try to run/debug, I get

> Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.ExceptionInInitializerError
> 	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
> Caused by: java.lang.ExceptionInInitializerError
> 	at fr.fxjavadevblog.xr.screens.loading.LoadingScreen.<init>(LoadingScreen.java:42)
> 	at fr.fxjavadevblog.xr.screens.XenonScreen.createScreen(XenonScreen.java:34)
> 	at fr.fxjavadevblog.xr.screens.MainControler.create(MainControler.java:84)
> 	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:149)
> 	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
> Caused by: com.badlogic.gdx.utils.GdxRuntimeException: com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load dependencies of asset: backgrounds/bombing-pixels-white.jpg
> 	... 5 more

??

**Comment by fxrobin** [comment]
You have to add the "xenon-reborn-reborn/assets" folder to your Java build path.

The gradle build file includes this directive, but it doesn't seem to detect it automatically. That's why you have to do this manually.

Tell me if it's ok.
Regards.

**Comment by fxrobin** [comment]
Just clone the lastest master and follow the lastest (updated) instructions from the README.md (or the homepage of this project).

Thanx.

**Comment by stef-pellegrino** [comment]
It works, thanks for this "reborn" ;)
